### PR TITLE
Event testing for payment registry

### PR DESCRIPTION
**Pull request by BreatheSmile**
Hi hi,

Issue #49 asks for event testing; here I implement this for payments_registry.js which tests paymentRegistry.sol.

I also fixed an error in payments_registry.js; deleting a payment called cancelPayment, now it calls deletePayment. I fixed some typos in the paymentRegistry.sol. I added truffle-assertions package so I also updated package.json. 

Since I did not really change any solidity code, I didn't run the result by solhint.

I also did not want to touch package-lock.json, but now that I added a package I think the package lock should be rebuilt from the main branch. Hope it is OK that I leave that to you.

Also sorry for the jumbled commit history, I'm still learning the ropes of git...

Let me know if you like the way I did this; if so I can do it for events in other contracts as well.

Cheers! - Jeroen

### CODE REVIEW

**Comment by kermankohli** [comment]
Hey man! We've made a bunch of changes to the executor tests lately, do you think you could double check if it's all ok?

**Comment by BreatheSmile** [comment]
Hey Kerman,

The updates broke the building process again for me. I am surprised to run into an issue like that. Could it be that there is room for improvement in your build testing?

I am missing "AION" resources, see the following errors:

> @8xprotocol/artifacts@0.6.7 build D:\SmartContractDev\monorepo\packages\artifacts
> npm run clean && tsc

> @8xprotocol/artifacts@0.6.7 clean D:\SmartContractDev\monorepo\packages\artifacts
> rimraf rm -rf dist

src/index.ts(32,39): error TS2307: Cannot find module './build/abi/ts-aion/ApprovedRegistry_Aion'.
src/index.ts(33,31): error TS2307: Cannot find module './build/abi/ts-aion/Executor_Aion'.
src/index.ts(34,38): error TS2307: Cannot find module './build/abi/ts-aion/PaymentRegistry_Aion'.
src/index.ts(35,36): error TS2307: Cannot find module './build/abi/ts-aion/StakeContract_Aion'.
src/index.ts(36,42): error TS2307: Cannot find module './build/abi/ts-aion/PayrollSubscription_Aion'.
src/index.ts(37,36): error TS2307: Cannot find module './build/abi/ts-aion/TransferProxy_Aion'.
src/index.ts(38,35): error TS2307: Cannot find module './build/abi/ts-aion/EightExToken_Aion'.
src/index.ts(39,27): error TS2307: Cannot find module './build/abi/ts-aion/WETH_Aion'.

Anyway, for my PR it looks like not many relevant things have changed. Just that the variable names are inconsistent; it used to be "subscriptionIdentifer" in paymentContract.sol, which I corrected to "subscriptionIdentifier" (with an extra 'i'), and now half of them have been renamed to "paymentIdentifier". Whatever the eventual naming, it needs to be reflected by updating the parameter names when querying the event in the test file (payment_registry.js).
I'll be back from holiday trip next week and can resolve the file conflicts, but I cannot run tests if the build is broken.

**Comment by kermankohli** [comment]
Hey, apologies for the breaking changes. For now the easiest way is to simply comment out lines 32 to 50 in `index.ts` in `artifacts/src`. I'll leave this issue open until it gets resolved properly!

**Comment by BreatheSmile** [comment]
Next step:

> > @8xprotocol/service-node-core@0.6.0 build D:\SmartContractDev\monorepo\packages\service-node-core
> > npm run clean && tsc
> 
> 
> > @8xprotocol/service-node-core@0.6.0 clean D:\SmartContractDev\monorepo\packages\service-node-core
> > rimraf -rf ./dist
> 
> src/services/aion_service.ts(8,10): error TS2724: Module '"D:/SmartContractDev/monorepo/packages/artifacts/dist/types/index"' has no exported member 'StakeContract_Aion'. Did you mean 'StakeContractAbi'?
> src/services/aion_service.ts(8,30): error TS2305: Module '"D:/SmartContractDev/monorepo/packages/artifacts/dist/types/index"' has no exported member 'WETH_Aion'.
> src/services/aion_service.ts(8,41): error TS2724: Module '"D:/SmartContractDev/monorepo/packages/artifacts/dist/types/index"' has no exported member 'Executor_Aion'. Did you mean 'ExecutorAbi'?
> src/services/aion_service.ts(8,56): error TS2724: Module '"D:/SmartContractDev/monorepo/packages/artifacts/dist/types/index"' has no exported member 'PayrollSubscription_Aion'. Did you mean 'PayrollSubscriptionAbi'?

**Comment by kermankohli** [comment]
Merged! Thanks for submitting this @BreatheSmile! Would love to have you contribute more if you're able to.

**Pull request merged**
